### ISSUE TITLE
Run Tests Synchronously without Redis Installed

### ISSUE THREAD

**Issue by epicserve** [ui/django-rq#106]
Running tests synchronously without Redis installed might be a good feature, especially if you're using a continuous integration service that doesn't have support for Redis.

**Comment by selwin** [comment]
I have never looked into this to be honest. Are you planning on using a library to mock Redis to achieve this?

**Comment by epicserve** [comment]
@selwin I was hoping you might have an idea on how to add this in as a feature. Maybe it's not needed ... maybe everyone just has Redis support with their CI service.

**Comment by changeaddress** [comment]
You should be able to use a free cloud redis db with your CI.  
I use Circle CI and set the below in `circle.yml`.

```yml
machine:
  # Override /etc/hosts
  hosts:
    circlehost: 127.0.0.1
    dev.mycompany.com: 127.0.0.1

  # Add some environment variables
  environment:
    CIRCLE_ENV: test
    DATABASE_URL_REDIS: <YOUR REDIS DB URL HERE>
```
